# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aztui < Formula
  desc "k9s-style terminal UI for Azure"
  homepage "https://github.com/GoosieZA/aztui"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.5.0/aztui_0.5.0_darwin_amd64.tar.gz"
      sha256 "f05cdcfc3936673ad68d123e8a202fa7dda00fcfa93caf38246f5aee74ff39ce"

      define_method(:install) do
        bin.install "aztui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.5.0/aztui_0.5.0_darwin_arm64.tar.gz"
      sha256 "2ac9788c66efc3eb5ca2919d294f179bec35e5843ad09503a2e608341d05c7a1"

      define_method(:install) do
        bin.install "aztui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.5.0/aztui_0.5.0_linux_amd64.tar.gz"
      sha256 "1f61ed12a228999256a0b9c6077dd4662eb38697bace528120fc04137b82542c"
      define_method(:install) do
        bin.install "aztui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.5.0/aztui_0.5.0_linux_arm64.tar.gz"
      sha256 "62bb445fe7e11bf0d0c6c1851e83e9dbd2d14f633ea834084faeec0fac2bae68"
      define_method(:install) do
        bin.install "aztui"
      end
    end
  end

  test do
    system "#{bin}/aztui", "--version"
  end
end
