# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aztui < Formula
  desc "k9s-style terminal UI for Azure"
  homepage "https://github.com/GoosieZA/aztui"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.4.0/aztui_0.4.0_darwin_amd64.tar.gz"
      sha256 "7fa466d8732e78f9cf2bbb7f99cb6ec09d54d1c69d320901ad5ead5e84ca3431"

      define_method(:install) do
        bin.install "aztui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.4.0/aztui_0.4.0_darwin_arm64.tar.gz"
      sha256 "37c7fe76098393e97f8111568c736cf947d73ceddfb40cf503fbcdd121a797dd"

      define_method(:install) do
        bin.install "aztui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.4.0/aztui_0.4.0_linux_amd64.tar.gz"
      sha256 "4fd20cd940fd5a4807b1ef580a4b6fb185e49d04c7f5c0c2aef46e6af4282d06"
      define_method(:install) do
        bin.install "aztui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.4.0/aztui_0.4.0_linux_arm64.tar.gz"
      sha256 "e9e8364ef267aff0b92e890450f274862dfcac7192394c022f682f2d9fd95ff8"
      define_method(:install) do
        bin.install "aztui"
      end
    end
  end

  test do
    system "#{bin}/aztui", "--version"
  end
end
