# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aztui < Formula
  desc "k9s-style terminal UI for Azure"
  homepage "https://github.com/GoosieZA/aztui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.2.0/aztui_0.2.0_darwin_amd64.tar.gz"
      sha256 "b34af787339869bfb7848d89b9615c93e94ef1a41fa9aa7e0b42d2c2391287c5"

      define_method(:install) do
        bin.install "aztui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.2.0/aztui_0.2.0_darwin_arm64.tar.gz"
      sha256 "4f7f022ad191f8905eda93f1931b5625f5f4fbb3e0f2873e5e76b243dc6cfbc7"

      define_method(:install) do
        bin.install "aztui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.2.0/aztui_0.2.0_linux_amd64.tar.gz"
      sha256 "5173c90194d8c5a010a5f4e4c3979eec315a7003bf6b3c92a0a84804b22389d3"
      define_method(:install) do
        bin.install "aztui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoosieZA/aztui/releases/download/v0.2.0/aztui_0.2.0_linux_arm64.tar.gz"
      sha256 "0a5ae76681d6e705c66965d665ec4c6aa2381c814ff7700a48da739b8cd1a35c"
      define_method(:install) do
        bin.install "aztui"
      end
    end
  end

  test do
    system "#{bin}/aztui", "--version"
  end
end
